name: agendadorcliente
description: "Agendador de barbearia"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  fluttertoast: ^8.2.8
  easy_stepper: ^0.8.5+1
  flutter_multi_formatter: ^2.13.0
  cached_network_image: ^3.4.1
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.2.0
  rflutter_alert: ^2.0.7
  js: ^0.7.1
  flutter_launcher_icons: ^0.14.4

  cupertino_icons: ^1.0.2
  go_router: ^14.6.2
  intl: ^0.20.1
  shimmer: ^3.0.0
  universal_html: ^2.2.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"   

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true